services:
  aurora-web:
    image: ghcr.io/aurora-site/aurora-web:${IMAGE_TAG:-latest}
    container_name: aurora-web
    restart: unless-stopped
    ports:
      - 127.0.0.1:${PORT:-8000}:8000
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
    labels:
      org.opencontainers.group: logging
