- name: Deploy {{ ENV_NAME }} aurora-api
  hosts: all
  become: false
  vars:
    project_dir: ~/deploy/{{ ENV_NAME }}-aurora-web

  tasks:
    - name: Create project directory
      ansible.builtin.file:
        path: "{{ project_dir }}"
        state: directory
        mode: "0755"

    - name: Copy files to service directory
      ansible.builtin.copy:
        src: "{{ ENV_NAME }}/{{ item }}"
        dest: "{{ project_dir }}/{{ item }}"
        mode: "0755"
      loop:
        - compose.yaml

    - name: Pull new image
      ansible.builtin.command:
        cmd: docker compose pull
        chdir: "{{ project_dir }}"
      environment:
        IMAGE_TAG: "{{ IMAGE_TAG }}"
      register: out
      changed_when: out.rc != 0

    - name: Deploy new image
      ansible.builtin.command:
        cmd: docker compose up -d --force-recreate
        chdir: "{{ project_dir }}"
      environment:
        PORT: "{{ PORT }}"
        IMAGE_TAG: "{{ IMAGE_TAG }}"
      register: out
      changed_when: out.rc != 0
